- hosts: all
  vars:
    synced_folder: /home/vagrant/playgrounds
    docker_users:
      - vagrant
  vars_files:
    - vars/third_party_playgrounds.yml
  roles:
    # Ansible role to install docker
    # https://galaxy.ansible.com/geerlingguy/docker
    - geerlingguy.docker

  tasks:
    - name: Create third party playground directory
      ansible.builtin.file:
        path: "{{ synced_folder }}/third_party"
        state: directory
    - name: Fetch third party playgrounds
      ansible.builtin.git:
        repo: "{{ item.src }}"
        dest: "{{ synced_folder }}/third_party/{{ item.name }}"
      loop: "{{ third_party_playgrounds }}"
