services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    entrypoint:
      - "/bin/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=playground
      - POSTGRES_PASSWORD=playground
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - 9093:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://playground@postgres:5432/playground?sslmode=disable
    depends_on:
      - postgres
