global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alert.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: service-a
    scrape_interval: 4s
    static_configs:
      - targets: ['service-a:5000']

  - job_name: service-b
    scrape_interval: 4s
    static_configs:
      - targets: ['service-b:5001']
