global:
  resolve_timeout: 10s
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'mail:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false
  #smtp_auth_username: 'alertmanager'
  #smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: team-a

receivers:
- name: team-a
  email_configs:
    - to: 'team-a+alerts@example.org'
