services:
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./alerting/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  prometheus:
    image: prom/prometheus:latest
    entrypoint:
      - "/bin/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./alerting/prometheus:/etc/prometheus:ro

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui